void grafico(){
  TCanvas *cepic = new TCanvas("cepic", "");
  TGraph *graph1 =new TGraphErrors("output.txt","%lg %lg %*lg %*lg %*lg %*lg"); 
  graph1->SetMarkerStyle(1);
  graph1->SetMarkerColor(kRed);
  graph1->SetLineColor(kRed);
  graph1->SetLineStyle(kRed);
  TGraph *graph2 =new TGraphErrors("output.txt","%*lg %*lg %lg %lg %*lg %*lg"); 
  graph2->SetMarkerStyle(1);
  graph2->SetMarkerColor(kBlue);
  graph2->SetLineColor(kBlue);
  graph2->SetLineStyle(kBlue);
  TGraph *graph3 =new TGraphErrors("output.txt","%*lg %*lg %*lg %*lg %lg %lg"); 
  graph3->SetMarkerStyle(1);
  graph3->SetMarkerColor(kGreen);
  graph3->SetLineColor(kGreen);
  graph3->SetLineStyle(kGreen);
  TMultiGraph *mg = new TMultiGraph ();
  mg->SetTitle(";Time;Cells");
  mg->Add(graph1, "PL");
  mg->Add(graph2, "PL");
  mg->Add(graph3, "PL");
  mg->Draw("APE");
 TLegend *leg=new TLegend(0.9,.8,.7,.9);
    leg->SetFillColor(0);
    leg->AddEntry(graph1 ,"Infected");
    leg->AddEntry(graph2, "Susceptible");
    leg->AddEntry(graph3, "Recovered");
    leg->Draw("Same");
}
